openapi: 3.0.3
info:
  title: Initiate payment
  description: "This API allows users to trigger an HMRC payment journey from their\
    \ software. \n\nThe workflow enables an API user to redirect a customer through\
    \ to an HMRC payment journey. \nIf an optional back-url was provided by the API\
    \ user we will offer this as a link to the customer to continue their journey.\n\
    \nAdditional details about the outcome of the payment can be discovered \nby the\
    \ API user by taking advantage of the /status endpoint.\n\nTypical lifetimes for\
    \ journey storage are not yet determined.\n"
  version: 1.0.3
servers:
- url: https://test-api.service.hmrc.gov.uk/payments/make-payment
  description: Sandbox
- url: https://api.service.hmrc.gov.uk/payments/make-payment
  description: Production
paths:
  /pay:
    post:
      summary: Begin a payment journey.
      description: |
        After a successful call to the /pay endpoint, the API user receives JSON with a redirection URL. The API user
        then redirects the customer's browser to this URL, starting the payment journey.
      requestBody:
        description: "The request body always contains the fields that allow HMRC\
          \ to identify the liability that is being paid, so \nthat the funds are\
          \ not mis-allocated. The required fields are the taxRegime, the reference\
          \ and amountInPence.\nThe backURL is an optional field containing a url\
          \ to return the user to after they finish their payment.\nThe friendlyName\
          \ is an optional field to let the user know where they are being returned\
          \ to after they finish their payment.\nIf a field is labeled as optional,\
          \ we intend this to mean that it should be *omitted entirely* - not sent\
          \ through with a null value etc.\n"
        content:
          application/json:
            schema:
              title: Pay request schema
              required:
              - amountInPence
              - reference
              - taxRegime
              type: object
              properties:
                taxRegime:
                  type: string
                  description: |
                    The tax regime under which the liability has arisen. One of a fixed set. Currently supported regimes are: Self Assessment and Vat.
                  example: SelfAssessment
                  enum:
                  - SelfAssessment
                  - Vat
                reference:
                  type: string
                  description: The reference identifying the tax liability. For Self
                    Assessment this is the 10 digit Unique Taxpayer Reference. For
                    VAT this is the 9-digit VAT registration number.
                  example: "1097172564"
                amountInPence:
                  minimum: 0
                  exclusiveMinimum: false
                  type: integer
                  description: "The amount to be paid in pence, so £12.34 is 1234,\
                    \ must be greater than or equal to 0. If 0 is provided, the user\
                    \ will be prompted to enter an amount. If non zero is provided,\
                    \ the user will be prompted to select the amount or enter another\
                    \ amount."
                  example: 1234
                backURL:
                  type: string
                  description: "If this is present HMRC will offer this as a link\
                    \ to the customer at the end of the journey, this link can allow\
                    \ them to return to their software."
                  format: uri
                  example: https://some-accounting-software.com/after-pay/a218f71d9bf2438e851c71d50866c2e9
                friendlyName:
                  type: string
                  description: "The name of the software that the user started their\
                    \ payment from. If this is present, then we will display a link\
                    \ to help users go back to their software which says \"return\
                    \ to &lt;friendlyName&gt;\""
                  example: Accounting Software Company X
              description: The JSON describing an HMRC third party payment /pay payload.
        required: true
      responses:
        "201":
          description: Created. Body contains url to redirect user to and a UUID to
            look up the status of the payment journey with.
          content:
            application/json:
              schema:
                type: object
                properties:
                  redirectURL:
                    type: string
                    description: The URL to direct the customer browser to in order
                      to initiate the customer payment journey
                  clientJourneyId:
                    type: string
                    description: "The client identifier created by HMRC for this journey.\
                      \ This will be a UUID (version 4, variant 2). This field is\
                      \ used to identify the journey in calls to the /status endpoint."
                    format: uuid
              example:
                redirectURL: https://tax.gov.uk/payments/start/jhdugiuygdwuygsxajvbh
                clientJourneyId: a218f71d-9bf2-438e-851c-71d50866c2e9
        "400":
          description: |
            Bad Request.

            A 400 response represents a malformed request. The returned JSON will attempt to guide
            the API user to the problem.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    description: The array contains the list of error messages.
                    items:
                      type: string
              example:
                errors:
                - Mandatory reference field was omitted.
        "500":
          description: An error occurred upstream and could not be recovered from.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    description: The array contains the list of error messages.
                    items:
                      type: string
              example:
                errors:
                - Error from upstream
      security:
      - applicationRestricted: []
  /status:
    get:
      summary: Discover the status of a payment.
      description: "The API user can check the payment status by providing the clientJourneyId\
        \ used \nwhen the payment journey was created.\nThe JSON body returned will\
        \ include the clientJourneyId, the taxRegime, the amountInPence paid and also\
        \ the paymentStatus.\n\n### Test data\nScenario simulation using Gov-Test-Scenario\
        \ headers is *only available in the sandbox environment*.\nYou will not be\
        \ able to access the frontend screens to complete the journey, but you can\
        \ use headers in the POST request \nto set a journey into a certain state.\
        \ To achieve this send a Gov-Test-Scenario header with a value matching one\
        \ of the values below. \n\n| Header Value (Gov-Test-Scenario) | Scenario description\
        \                                        |\n| --------------------------------\
        \ | ----------------------------------------------------------- |\n| COMPLETED\
        \                        | The payment has completed and the transfer is made.\
        \         |\n| FAILED                           | The payment has failed for\
        \ one of the following reasons: <br> - The payment was cancelled by the user\
        \ or timed out at the bank during the payment process. <br> - The bank or\
        \ building society has rejected the payment. <br> - The payment has failed\
        \ due to an error. |\n| IN_PROGRESS                      | The payment is\
        \ in progress but has not completed or failed. |\n"
      parameters:
      - name: clientJourneyId
        in: query
        description: The identifier for the payment journey.
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: uuid
          example: a218f71d-9bf2-438e-851c-71d50866c2e9
      responses:
        "200":
          description: |
            A payment matching the query was found and the details returned in the JSON response
          content:
            application/json:
              schema:
                required:
                - amountInPence
                - clientJourneyId
                - paymentStatus
                - taxRegime
                type: object
                properties:
                  clientJourneyId:
                    type: string
                    description: The identifier for the payment journey.
                    example: a218f71d-9bf2-438e-851c-71d50866c2e9
                  taxRegime:
                    type: string
                    description: The tax regime under which the liability has arisen.
                      One of a fixed set.
                    example: SelfAssessment
                    enum:
                    - SelfAssessment
                    - Vat
                  amountInPence:
                    type: integer
                    description: "Represents the amount actually paid, in pence."
                    example: 3456
                  paymentStatus:
                    type: string
                    description: |
                      The status of the payment within the HMRC system.
                    example: Completed
                    enum:
                    - Completed
                    - Failed
                    - InProgress
              example:
                clientJourneyId: a218f71d-9bf2-438e-851c-71d50866c2e9
                taxRegime: SelfAssessment
                amountInPence: 1453
                paymentStatus: Completed
        "400":
          description: |
            A malformed request. The returned JSON will attempt to guide
            the API user to the problem.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      An error containing what may be wrong with the request.
              example:
                error: Mandatory clientJourneyId field of query was omitted.
        "404":
          description: |
            Either the payment journey never existed, or HMRC no longer has a record of the journey.
      security:
      - applicationRestricted: []
components:
  parameters:
    acceptHeader:
      name: Accept
      in: header
      required: true
      style: simple
      explode: false
      schema:
        type: string
        enum:
        - application/vnd.hmrc.1.0+json
    contentTypeJsonHeader:
      name: Content-Type
      in: header
      description: |
        Specifies the format of the request body, which must be JSON.
      required: true
      style: simple
      explode: false
      schema:
        type: string
        enum:
        - application/json
    authorizationHeader:
      name: Authorization
      in: header
      description: |
        An OAuth 2.0 Bearer Token.
      required: true
      style: simple
      explode: false
      schema:
        type: string
        example: Bearer bb7fed3fe10dd235a2ccda3d50fb
  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            status: Update the status of fraud check
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: {}
